### ISSUE TITLE
git-ignore .DS_Store

### ISSUE THREAD

**Issue by lganzzzo** [42yeah/Penefiles#1]
Hello guys,

Nice project, I'm pleased to see Oat++ serving backend for it!

Don't forget to clean .DS_Store files and ignore them

**Comment by 42yeah** [comment]
Hi, thanks for the headsup! All `.DS_Store`s were removed in the latest commit. I somehow forgot to reply until now, sorry.

Also, thank you for the awesome Oat++, which kept this thing up & running for a full year :)
